homepage: https://github.com/nerdrew/dart-ctags
description: ctags compatible tag file generator for dart code
name: dart_ctags
version: 1.2.0
environment:
    sdk: ">=2.0.0 <3.0.0"
executables:
    dart_ctags: tags
dependencies:
    analyzer: ^0.40.0
    path: ^1.7.0
    quiver: ^2.1.3
    args: ^1.6.0
dev_dependencies:
    pedantic: ^1.9.2
